module.exports = {
    'evenOddHeading' : '//div[@class = "puzzleBox evenAndOddPB"]//h4[1]',
    'evenOddInput' : 'input[name="evenOddInput"]',
    'evenOddButton' : 'button[name="evenOddButton"]',
    'evenResults' : 'span[name="evenResults"]',
    'oddResults' : 'span[name="oddResults"]',
    'filterObjectHeading' : '//div[@class = "puzzleBox filterObjectPB"]//h4[1]',
    'objectFilterArray' : 'span[name="objectFilterObjects"]',
    'objectFilterInput' : 'input[name="objectFilterInput"]',
    'objectFilterButton' : 'button[name="objectFilterButton"]',
    'objectFilterResults' : 'span[name="objectFilterResults"]',
    'filterStringHeading' : '//div[@class = "puzzleBox filterObjectPB"]//h4[1]',
    'nameFilterArray' : 'span[name="nameFilterNames"]',
    'nameFilterInput' : 'input#nameFilterInput',
    'nameFilterButton' : 'button#nameFilterButton',
    'nameFilterResults' : 'span[name="nameFilterResults"]',
    'palindromeHeading' : '//div[@class = "puzzleBox palindromePB"]//h4[1]',
    'palindromeInput' : 'input[name="palindromeInput"]',
    'palindromeButton' : 'button[name="palindromeButton"]',
    'palindromeResults' : 'span[name="palindromeResults"]',
    'sumHeading' : '//div[@class = "puzzleBox sumPB"]//h4[1]',
    'sumInput1' : 'input[name="sumInput1"]',
    'sumInput2' : 'input[name="sumInput2"]',
    'sumButton' : 'button[name="sumButton"]',
    'sumResults' : 'span[name="sumResults"]'
}